// AUTO-GENERATED by scripts/parse-paldb.py + emit-paldb.py.
// Join key is internalName. Do not hand-edit.
// PalDB pages fetched: 2026-08-19; displayed version: v1.0.3 2026/8/12
// Work suitability: PalCalc db.json v27 fetched 2026-08-19.
// This file emitted: 2026-08-19
export interface DataGap {
  internalName: string;
  field: string;
  reason: string;
}

export const DATA_GAPS: DataGap[] = [{"field": "work", "internalName": "WorldTreeDragon", "reason": "absent from the PalCalc game-file export; no source-of-truth work record"}, {"field": "elements", "internalName": "WorldTreeDragon", "reason": "absent from the Stats/Other sections"}, {"field": "work", "internalName": "WorldTreeDragon", "reason": "absent from the PalDB work container"}];
