// Full pair-space lookup tables for the /data-check diagnostics page.
//
// Building these runs resolveChild over all ~45k unordered pairs (~11M rank
// comparisons, ~160ms on desktop and several hundred ms on mobile). They used
// to live in the barrel (index.ts), which made every consumer of the dataset —
// including the pathfinder worker on every spawn — pay that cost at module
// init. Nothing outside /data-check reads them, so they live here and the
// price is only paid when that route actually loads.
import { PALS } from "./pals";
import { UNIQUE_COMBOS } from "./uniqueCombos";
import { resolveChild } from "./breeding";

// pairToChild — every unordered pair (p1<=p2) plus both directions for order-sensitive combos.
// GENERATED by running resolveChild over the full pair space. Do not hand-edit.
// Expected pair count: PALS.length * (PALS.length + 1) / 2 unordered pairs
// plus (# order-sensitive combos) extra reversed-direction entries.
export const pairToChild: Map<string, number> = (() => {
  const map = new Map<string, number>();
  const ids = PALS.map((p) => p.id).sort((a, b) => a - b);
  for (let i = 0; i < ids.length; i++) {
    for (let j = i; j < ids.length; j++) {
      const a = ids[i];
      const b = ids[j];
      const res = resolveChild(a, b);
      if (res) map.set(`${a}:${b}`, res.childId);
    }
  }
  // Also record reverse direction for order-sensitive combos.
  for (const c of UNIQUE_COMBOS) {
    if (c.orderSensitive) {
      const res = resolveChild(c.parent1Id, c.parent2Id);
      if (res) map.set(`${c.parent1Id}->${c.parent2Id}`, res.childId);
    }
  }
  return map;
})();

// childToParents — inverted pairToChild
export const childToParents: Map<number, Array<[number, number]>> = (() => {
  const map = new Map<number, Array<[number, number]>>();
  for (const [key, childId] of pairToChild.entries()) {
    const sep = key.includes("->") ? "->" : ":";
    const [aStr, bStr] = key.split(sep);
    const a = Number(aStr);
    const b = Number(bStr);
    const list = map.get(childId) ?? [];
    list.push([a, b]);
    map.set(childId, list);
  }
  return map;
})();
