// AUTO-GENERATED by scripts/parse-paldb.py + emit-paldb.py.
// Join key is internalName. Do not hand-edit.
// PalDB pages fetched: 2026-08-19; displayed version: v1.0.3 2026/8/12
// Work suitability: PalCalc db.json v27 fetched 2026-08-19.
// This file emitted: 2026-08-19
export interface RaidBossEvidence {
  sourceId: string;
  name: string;
  level: number | null;
  sourceUrl: string;
}

export const PAL_RAID_BOSSES: Record<string, readonly RaidBossEvidence[]> = {"DarkMechaDragon": [{"level": 65, "name": "Invader from Space Xenolord", "sourceId": "RAID_DarkMechaDragon", "sourceUrl": "https://paldb.cc/en/Raid"}, {"level": 80, "name": "Invader from Space (Ultra) Xenolord", "sourceId": "RAID_DarkMechaDragon_2", "sourceUrl": "https://paldb.cc/en/Raid"}], "KingBahamut_Dragon": [{"level": 55, "name": "Incarnation of the Eternal Flame Blazamut Ryu", "sourceId": "RAID_KingBahamut_Dragon", "sourceUrl": "https://paldb.cc/en/Raid"}, {"level": 80, "name": "Incarnation of the Eternal Flame (Ultra) Blazamut Ryu", "sourceId": "RAID_KingBahamut_Dragon_2", "sourceUrl": "https://paldb.cc/en/Raid"}], "LegendDeer": [{"level": 70, "name": "King of Salvation Hartalis", "sourceId": "RAID_LegendDeer", "sourceUrl": "https://paldb.cc/en/Raid"}, {"level": 80, "name": "King of Salvation (Ultra) Hartalis", "sourceId": "RAID_LegendDeer_2", "sourceUrl": "https://paldb.cc/en/Raid"}], "NightLady": [{"level": 35, "name": "Eclipsed Siren Bellanoir", "sourceId": "RAID_NightLady", "sourceUrl": "https://paldb.cc/en/Raid"}], "NightLady_Dark": [{"level": 45, "name": "Twilight Siren Bellanoir Libero", "sourceId": "RAID_NightLady_Dark", "sourceUrl": "https://paldb.cc/en/Raid"}, {"level": 80, "name": "Twilight Siren (Ultra) Bellanoir Libero", "sourceId": "RAID_NightLady_Dark_2", "sourceUrl": "https://paldb.cc/en/Raid"}]};

/** PalDB Summoning Altar cards that have no corresponding entry in PALS. */
export const NON_ROSTER_RAID_CARDS: readonly RaidBossEvidence[] = [{"level": 50, "name": "Moon Lord", "sourceId": "RAID_YakushimaBoss002", "sourceUrl": "https://paldb.cc/en/Raid"}, {"level": 80, "name": "[Master] Moon Lord", "sourceId": "RAID_YakushimaBoss002_2", "sourceUrl": "https://paldb.cc/en/Raid"}];

export const RAID_PROVENANCE = {"sourceTier": 3, "sourceUrl": "https://paldb.cc/en/Raid", "fetchedAt": "2026-08-19T23:20:11+00:00", "paldbVersion": {"date": "2026/8/12", "version": "v1.0.3"}};

export function raidBossesOf(internalName: string): readonly RaidBossEvidence[] {
  return PAL_RAID_BOSSES[internalName] ?? [];
}
