"""Emit source-backed Palworld technology unlock records.

Technology unlock tiles are sourced only from PalDB's exact, heading-bounded
Technology /80 catalogue. This generator does not invent craft recipes, item
stats, or unlock prerequisites beyond the values rendered on each tile.
"""
from __future__ import annotations

import datetime as dt
import json
import re
import sys
from pathlib import Path
from urllib.request import Request, urlopen

from bs4 import BeautifulSoup, Tag

from palworld_source_contracts import SourceContractError, require_exact_section

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "src" / "data" / "palworld"
URL = "https://paldb.cc/en/Technologies"
CACHE = ROOT / "scripts" / ".cache" / "knowledge-technologies.html"
COVERAGE = DATA / "knowledgeTechnologies.coverage.json"
BASELINE = ROOT / "scripts" / "coverage-baselines" / "knowledge-technologies.json"


def normalized(tag: Tag | None) -> str:
    return " ".join(tag.get_text(" ", strip=True).split()) if tag is not None else ""


def fetch() -> str:
    request = Request(URL, headers={"User-Agent": "good-vibe-desk data generator/1.0"})
    with urlopen(request, timeout=30) as response:
        body = response.read().decode("utf-8")
    CACHE.parent.mkdir(parents=True, exist_ok=True)
    CACHE.write_text(body)
    return body


def main() -> None:
    soup = BeautifulSoup(fetch(), "html.parser")
    section = require_exact_section(soup, page=URL, title="Technology /80")
    rows: list[Tag] = []
    for node in section.nodes:
        rows.extend(node.select("div.col.pt-2.pb-1.border-bottom"))
    if not rows:
        raise SourceContractError(f"{URL}: Technology /80 has no bounded technology rows.")

    records: list[dict[str, object]] = []
    for row in rows:
        level_node = row.select_one(":scope > div.d-flex.flex-wrap > div.d-flex.justify-content-center")
        level_text = normalized(level_node)
        if not re.fullmatch(r"[1-9][0-9]*", level_text):
            raise SourceContractError(f"{URL}: technology row has invalid level marker {level_text!r}.")
        level = int(level_text)
        tiles = row.select(":scope > div.d-flex.flex-wrap > div.hoverTech[data-hover]")
        if not tiles:
            raise SourceContractError(f"{URL}: Technology level {level} row has no unlock tiles.")
        for tile in tiles:
            category = normalized(tile.select_one(".hoverTechHeader"))
            name = normalized(tile.select_one(".hoverTechFooter"))
            cost_text = normalized(tile.select_one(".hoverTechCost"))
            source_key = tile.get("data-hover", "")
            if not category or not name or not re.fullmatch(r"[1-9][0-9]*", cost_text) or not source_key.startswith("?s=Technology/"):
                raise SourceContractError(
                    f"{URL}: invalid technology tile at level {level}: category={category!r}, name={name!r}, cost={cost_text!r}, key={source_key!r}."
                )
            records.append({"level": level, "category": category, "name": name, "technologyPointCost": int(cost_text), "sourceKey": source_key.removeprefix("?s=Technology/")})
    ids = [f"technology:{record['sourceKey']}" for record in records]
    if len(ids) != len(set(ids)):
        duplicates = sorted({item for item in ids if ids.count(item) > 1})
        raise SourceContractError(f"{URL}: technology records have duplicate source keys: {duplicates[:5]}.")

    emitted_at = dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    categories: dict[str, int] = {}
    for record in records:
        categories[record["category"]] = categories.get(record["category"], 0) + 1
    payload = []
    source = {"id": "paldb-technologies", "url": URL, "tier": "wiki", "locator": "Technology /80 unlock tiles", "observedAt": emitted_at, "sourceVersion": "v1.0.3"}
    for record in records:
        payload.append({
            "id": f"technology:{record['sourceKey']}",
            "data": record,
            "version": {"gameVersion": "v1.0.3", "emittedAt": emitted_at, "generatorVersion": "paldb-technologies"},
            "sources": [source],
            "provenance": [{"field": key, "sourceIds": [source["id"]], "confidence": "corroborated"} for key in record],
            "gaps": [{"field": "craftRecipe", "reason": "Technology tiles identify an unlock, category, level, and point cost but do not expose a complete crafting recipe in this bounded catalogue.", "resolution": "Extract the matching item or structure page under its own card contract."}],
        })
    coverage = {"dataset": "knowledge-technologies", "generatedAt": emitted_at, "gameVersion": "v1.0.3", "recordCount": len(payload), "counts": {"technologyLevels": len(rows), **categories}, "sourceUrls": [URL]}
    body = "// AUTO-GENERATED by scripts/emit-knowledge-technologies.py. Do not hand-edit.\n" + f"// Source: {URL}; emitted: {emitted_at}.\n" + 'import type { EvidenceRecord } from "./knowledge";\n\n' + "export interface TechnologyKnowledge {\n  level: number;\n  category: string;\n  name: string;\n  technologyPointCost: number;\n  sourceKey: string;\n}\n\n" + "export const PALWORLD_TECHNOLOGIES: readonly EvidenceRecord<TechnologyKnowledge>[] = " + json.dumps(payload, ensure_ascii=False) + ";\n"
    (DATA / "knowledgeTechnologies.ts").write_text(body)
    COVERAGE.write_text(json.dumps(coverage, indent=2) + "\n")
    BASELINE.parent.mkdir(parents=True, exist_ok=True)
    if not BASELINE.exists():
        BASELINE.write_text(json.dumps(coverage, indent=2) + "\n")
    print(f"wrote knowledgeTechnologies.ts: {len(payload)} unlocks across {len(rows)} levels")


if __name__ == "__main__":
    try:
        main()
    except SourceContractError as error:
        print(f"[emit-knowledge-technologies] FAILED: {error}", file=sys.stderr)
        raise SystemExit(1)
