"""Emit source-backed Pal skill and element knowledge artifacts.

This generator deliberately preserves Partner Skill prose and range text rather
than pretending every Level 1–5 value or stacking rule has been extracted. The
next source pass may add structured effect fields only with per-field evidence.
"""
from __future__ import annotations

import datetime as dt
import json
import re
import sys
from pathlib import Path
from urllib.request import Request, urlopen

from bs4 import BeautifulSoup

from palworld_source_contracts import SourceContractError, require_exact_section

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "src" / "data" / "palworld"
CACHE = ROOT / "scripts" / ".cache" / "paldb-parsed.json"
MANIFEST = ROOT / "scripts" / ".cache-manifest.json"
PARTNER_URL = "https://paldb.cc/en/Partner_Skill"
PARTNER_CACHE = ROOT / "scripts" / ".cache" / "partner-skills.html"
COVERAGE = DATA / "knowledgeSkills.coverage.json"
BASELINE = ROOT / "scripts" / "coverage-baselines" / "knowledge-skills.json"


def fetch_partner_html() -> str:
    request = Request(PARTNER_URL, headers={"User-Agent": "good-vibe-desk data generator/1.0"})
    with urlopen(request, timeout=30) as response:
        body = response.read().decode("utf-8")
    PARTNER_CACHE.parent.mkdir(parents=True, exist_ok=True)
    PARTNER_CACHE.write_text(body)
    return body


def parse_partner_cards(html: str) -> dict[str, dict[str, object]]:
    soup = BeautifulSoup(html, "html.parser")
    titles = [" ".join(heading.get_text(" ", strip=True).split()) for heading in soup.find_all(["h1", "h2", "h3", "h4", "h5", "h6"])]
    matches = [title for title in titles if re.fullmatch(r"Partner Skill /[1-9][0-9]*", title)]
    if len(matches) != 1:
        raise SourceContractError(
            f"{PARTNER_URL}: expected exactly one declared Partner Skill catalogue heading; found {len(matches)}."
        )
    section_title = matches[0]
    expected_count = int(section_title.rsplit("/", 1)[1])
    section = require_exact_section(soup, page=PARTNER_URL, title=section_title)
    cards: dict[str, dict[str, object]] = {}
    for node in section.nodes:
        for card in node.select("div.col > div.card.itemPopup"):
            pal = card.select_one("a[data-pal-id]")
            if pal is None:
                raise SourceContractError(f"{PARTNER_URL}: Partner Skill card is missing data-pal-id.")
            internal_name = pal["data-pal-id"]
            if internal_name in cards:
                raise SourceContractError(
                    f"{PARTNER_URL}: duplicate Partner Skill card for {internal_name!r}."
                )
            text = " ".join(card.get_text(" ", strip=True).split())
            match = re.search(r"Partner Skill\s+(.+?)\s+Lv\.1\s+(.+)$", text)
            if match is None:
                raise SourceContractError(
                    f"{PARTNER_URL}: card for {internal_name!r} lacks a parseable Partner Skill name/effect."
                )
            cards[internal_name] = {"name": match.group(1), "description": match.group(2)}
    if len(cards) != expected_count:
        raise SourceContractError(
            f"{PARTNER_URL}: expected {expected_count} Partner Skill cards; found {len(cards)}."
        )
    return cards


def js(value: object) -> str:
    return json.dumps(value, ensure_ascii=False)


def main() -> None:
    records = json.loads(CACHE.read_text())["records"]
    manifest = json.loads(MANIFEST.read_text())
    paldb = manifest["paldb"]
    displayed = paldb.get("displayedVersion", {})
    with_partner = [record for record in records.values() if record.get("partnerSkill")]
    partner_cards = parse_partner_cards(fetch_partner_html())
    expected_names = {record["internalName"] for record in with_partner}
    missing = sorted(expected_names - set(partner_cards))
    extra = sorted(set(partner_cards) - expected_names)
    if extra:
        raise SourceContractError(
            f"{PARTNER_URL}: catalogue contains cards absent from the local PalDB cache: {extra[:5]}."
        )

    emitted_at = dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    game_version = displayed.get("version", "UNKNOWN")
    out: list[str] = [
        "// AUTO-GENERATED by scripts/emit-knowledge-skills.py. Do not hand-edit.",
        f"// PalDB Partner Skill catalogue: {PARTNER_URL}; displayed version: {game_version} {displayed.get('date', '')}.",
        f"// Emitted: {emitted_at}.",
        'import type { EvidenceRecord } from "./knowledge";',
        "",
        "export interface PalSkillKnowledge {",
        "  internalName: string;",
        "  displayName: string;",
        "  elements: readonly string[];",
        "  activeSkills: readonly { level: number; name: string; element?: string; power?: number; cooldown?: number }[];",
        "  partnerSkill?: { name: string; description: string };",
        "}",
        "",
        "export const PAL_SKILL_KNOWLEDGE: Record<string, EvidenceRecord<PalSkillKnowledge>> = {",
    ]
    for internal_name in sorted(records):
        record = records[internal_name]
        source = {"id": "paldb-pal", "url": record["sourceUrl"], "tier": "wiki", "observedAt": emitted_at, "sourceVersion": game_version}
        data: dict[str, object] = {
            "internalName": internal_name,
            "displayName": record["displayName"],
            "elements": record["elements"],
            "activeSkills": record["activeSkills"],
        }
        provenance = [
            {"field": "displayName", "sourceIds": ["paldb-pal"], "confidence": "corroborated"},
            {"field": "elements", "sourceIds": ["paldb-pal"], "confidence": "corroborated"},
            {"field": "activeSkills", "sourceIds": ["paldb-pal"], "confidence": "corroborated"},
        ]
        gaps: list[dict[str, str]] = []
        if internal_name in partner_cards:
            card = partner_cards[internal_name]
            data["partnerSkill"] = card
            source = [source, {"id": "paldb-partner-catalogue", "url": PARTNER_URL, "tier": "wiki", "observedAt": emitted_at, "sourceVersion": game_version}]
            provenance.append({"field": "partnerSkill", "sourceIds": ["paldb-partner-catalogue"], "confidence": "corroborated"})
            gaps.append({"field": "partnerSkill.levels", "reason": "Catalogue card supplies Level 1 text/range only; exact Level 1–5 values are not yet bounded-extracted.", "resolution": "Extract a source that publishes per-level values with card-level contracts."})
            gaps.append({"field": "partnerSkill.stacking", "reason": "Stacking text is preserved in the raw description but not normalized into a reliable boolean.", "resolution": "Add a bounded parser and tests for explicit stacking language."})
        elif record.get("partnerSkill"):
            data["partnerSkill"] = {"name": record["partnerSkill"], "description": ""}
            provenance.append({"field": "partnerSkill.name", "sourceIds": ["paldb-pal"], "confidence": "reported"})
            gaps.append({"field": "partnerSkill", "reason": "The Pal-specific cache names a Partner Skill, but the current Partner Skill catalogue has no matching card.", "resolution": "Inspect the Pal page and catalogue after the next source/version update; do not infer the missing effect."})
        payload = {"id": f"pal-skill:{internal_name}", "data": data, "version": {"gameVersion": game_version, "emittedAt": emitted_at, "generatorVersion": "paldb-parsed-cache"}, "sources": source if isinstance(source, list) else [source], "provenance": provenance, "gaps": gaps or None}
        if payload["gaps"] is None:
            del payload["gaps"]
        out.append(f"  {js(internal_name)}: {js(payload)},")
    out.extend(["};", ""])
    (DATA / "knowledgeSkills.ts").write_text("\n".join(out))

    coverage = {"dataset": "knowledge-skills", "generatedAt": emitted_at, "gameVersion": game_version, "recordCount": len(records), "counts": {"withPartnerSkill": len(with_partner), "partnerSkillCards": len(partner_cards), "partnerSkillCatalogueGaps": len(missing), "withoutPartnerSkill": len(records) - len(with_partner), "activeSkillRecords": sum(bool(record["activeSkills"]) for record in records.values())}, "sourceUrls": [PARTNER_URL, "https://paldb.cc/"]}
    COVERAGE.write_text(json.dumps(coverage, indent=2) + "\n")
    BASELINE.parent.mkdir(parents=True, exist_ok=True)
    if not BASELINE.exists():
        BASELINE.write_text(json.dumps(coverage, indent=2) + "\n")
    print(f"wrote knowledgeSkills.ts: {coverage['recordCount']} Pals; {coverage['counts']['partnerSkillCards']} catalogue cards; {coverage['counts']['partnerSkillCatalogueGaps']} explicit catalogue gaps")


if __name__ == "__main__":
    try:
        main()
    except SourceContractError as error:
        print(f"[emit-knowledge-skills] FAILED: {error}", file=sys.stderr)
        raise SystemExit(1)
