#!/usr/bin/env python3
"""Emit Palworld data modules from the validated local source cache.

PalDB supplies page-derived fields. PalCalc's game-file export is the authority
for work suitability and is merged by ``parse-paldb.py`` before this script runs.
All joins use ``internalName``.
"""
from __future__ import annotations

import datetime as dt
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "src" / "data" / "palworld"
CACHE = ROOT / "scripts" / ".cache" / "paldb-parsed.json"
TOWER_CACHE = ROOT / "scripts" / ".cache" / "tower-bosses.json"
RAID_CACHE = ROOT / "scripts" / ".cache" / "raid-bosses.json"
DUNGEON_CACHE = ROOT / "scripts" / ".cache" / "dungeon-bosses.json"
MANIFEST = ROOT / "scripts" / ".cache-manifest.json"

dataset = json.loads(CACHE.read_text())
recs, gaps = dataset["records"], dataset["gaps"]
tower_payload = json.loads(TOWER_CACHE.read_text()) if TOWER_CACHE.exists() else {"records": [], "excluded": {}}
tower_records = tower_payload["records"]
tower_excluded = tower_payload["excluded"]
raid_payload = json.loads(RAID_CACHE.read_text()) if RAID_CACHE.exists() else {"joined": {}, "unmatched": []}
raid_records = raid_payload["joined"]
raid_unmatched = raid_payload["unmatched"]
dungeon_payload = json.loads(DUNGEON_CACHE.read_text()) if DUNGEON_CACHE.exists() else {"joined": {}, "families": []}
dungeon_records = dungeon_payload["joined"]
dungeon_families = dungeon_payload["families"]
keys = sorted(recs)
manifest = json.loads(MANIFEST.read_text()) if MANIFEST.exists() else {}
paldb = manifest.get("paldb", {})
palcalc = manifest.get("palcalc", {})
paldb_version = paldb.get("displayedVersion", {})


def date_part(value: str | None) -> str:
    return value.split("T", 1)[0] if value else "unknown"


PALDB_SCRAPED_AT = date_part(
    max((page.get("fetchedAt", "") for page in paldb.get("pages", {}).values()), default="")
)
PALCALC_FETCHED_AT = date_part(palcalc.get("fetchedAt"))
GENERATED_AT = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d")
HEAD = (
    "// AUTO-GENERATED by scripts/parse-paldb.py + emit-paldb.py.\n"
    "// Join key is internalName. Do not hand-edit.\n"
    f"// PalDB pages fetched: {PALDB_SCRAPED_AT}; displayed version: {paldb_version.get('version', 'unknown')} {paldb_version.get('date', '')}\n"
    f"// Work suitability: PalCalc db.json {palcalc.get('dbVersion', 'unknown')} fetched {PALCALC_FETCHED_AT}.\n"
    f"// This file emitted: {GENERATED_AT}\n"
)


def j(value: object) -> str:
    return json.dumps(value, ensure_ascii=False)


def write(name: str, body: str) -> None:
    (DATA / name).write_text(HEAD + body)
    print("wrote", name)


# elements
lines = [f"  {j(key)}: {j(recs[key]['elements'])}," for key in keys]
write(
    "elements.ts",
    "export const PAL_ELEMENTS: Record<string, readonly string[]> = {\n"
    + "\n".join(lines)
    + "\n};\n\n"
    "export function elementsOf(internalName: string): readonly string[] {\n"
    "  return PAL_ELEMENTS[internalName] ?? [];\n}\n",
)

# stats. A Pal absent from PalCalc has no source-of-truth work/stat record and
# deliberately remains absent from PAL_STATS rather than receiving a hand-made
# override. That preserves the app's "cannot compute" semantics.
stat_keys = [key for key in keys if recs[key].get("hasPalcalcWork")]
lines = []
for key in stat_keys:
    record = recs[key]
    lines.append(
        "  %s: %s,"
        % (
            j(key),
            j(
                {
                    "stats": {name: value for name, value in record["stats"].items() if value is not None},
                    "movement": {name: value for name, value in record["movement"].items() if value is not None},
                    "work": record["work"],
                    "genus": record.get("genus"),
                    "foodAmount": record.get("foodAmount"),
                    "nocturnal": record.get("nocturnal", False),
                }
            ),
        )
    )
write(
    "stats.ts",
    "export interface PalStatBlock {\n"
    "  stats: Record<string, number | string>;\n"
    "  movement: Record<string, number>;\n"
    "  work: { work: string; level: number }[];\n"
    "  genus?: string | null;\n"
    "  foodAmount?: number | null;\n"
    "  nocturnal: boolean;\n}\n\n"
    "export const PAL_STATS: Record<string, PalStatBlock> = {\n"
    + "\n".join(lines)
    + "\n};\n\n"
    "export function workLevel(internalName: string, work: string): number {\n"
    "  return PAL_STATS[internalName]?.work.find((entry) => entry.work === work)?.level ?? 0;\n}\n",
)

# spawns
lines = [f"  {j(key)}: {j(recs[key]['spawns'])}," for key in keys]
write(
    "spawns.ts",
    "export interface SpawnPoint {\n  area: string;\n  coords?: number[];\n"
    "  level?: number;\n  kind?: string;\n}\n\n"
    "export const PAL_SPAWNS: Record<string, SpawnPoint[]> = {\n"
    + "\n".join(lines)
    + "\n};\n\n"
    "export function spawnsOf(internalName: string): SpawnPoint[] {\n"
    "  return PAL_SPAWNS[internalName] ?? [];\n}\n\n"
    "/** A Pal with no field spawner can only be obtained by breeding/eggs. */\n"
    "export function isBreedOnly(internalName: string): boolean {\n"
    "  return spawnsOf(internalName).every((spawn) => spawn.kind === \"egg\");\n}\n",
)

# tower acquisition evidence
tower_by_pal: dict[str, list[dict]] = {}
for tower in tower_records:
    tower_by_pal.setdefault(tower["internalName"], []).append(tower)
tower_sources = manifest.get("towerSources", {}).get("sources", {})
write(
    "towers.ts",
    "export interface TowerEvidenceSource {\n  name: string;\n  url: string;\n}\n\n"
    "export interface TowerBossEvidence {\n"
    "  tower: string;\n  region: string;\n  coordinates: string;\n  leader: string;\n  pal: string;\n"
    "  internalName: string;\n  normalLevel: number;\n  hardModeLevel: number;\n"
    "  sourceTier: 3;\n  sourceKind: \"wiki-corroborated\";\n  sources: readonly [TowerEvidenceSource, TowerEvidenceSource];\n}\n\n"
    "export const PAL_TOWER_BOSSES: Record<string, readonly TowerBossEvidence[]> = "
    + j(tower_by_pal)
    + ";\n\n"
    "export const TOWER_SOURCE_EXCLUSIONS = "
    + j(tower_excluded)
    + ";\n\n"
    "export const TOWER_PROVENANCE = "
    + j(
        {
            "sourceTier": 3,
            "sourceKind": "wiki-corroborated",
            "sourceCount": len(tower_sources),
            "entryCount": len(tower_records),
            "sources": [source.get("url") for source in tower_sources.values()],
        }
    )
    + ";\n\n"
    "export function towerBossesOf(internalName: string): readonly TowerBossEvidence[] {\n"
    "  return PAL_TOWER_BOSSES[internalName] ?? [];\n}\n",
)

# raid acquisition evidence
raid_source = paldb.get("acquisitionPages", {}).get("raid", {})
write(
    "raid.ts",
    "export interface RaidBossEvidence {\n"
    "  sourceId: string;\n  name: string;\n  level: number | null;\n  sourceUrl: string;\n}\n\n"
    "export const PAL_RAID_BOSSES: Record<string, readonly RaidBossEvidence[]> = "
    + j(raid_records)
    + ";\n\n"
    "/** PalDB Summoning Altar cards that have no corresponding entry in PALS. */\n"
    "export const NON_ROSTER_RAID_CARDS: readonly RaidBossEvidence[] = "
    + j(raid_unmatched)
    + ";\n\n"
    "export const RAID_PROVENANCE = "
    + j(
        {
            "sourceTier": 3,
            "sourceUrl": raid_source.get("url", "https://paldb.cc/en/Raid"),
            "fetchedAt": raid_source.get("fetchedAt"),
            "paldbVersion": raid_source.get("paldbVersion"),
        }
    )
    + ";\n\n"
    "export function raidBossesOf(internalName: string): readonly RaidBossEvidence[] {\n"
    "  return PAL_RAID_BOSSES[internalName] ?? [];\n}\n",
)

# dungeon acquisition evidence
dungeon_source = paldb.get("acquisitionPages", {}).get("dungeons", {})
write(
    "dungeons.ts",
    "export interface DungeonBossEvidence {\n"
    "  sourceId: string;\n  name: string;\n  dungeon: string;\n  dungeonLevel: number;\n"
    "  minLevel: number;\n  maxLevel: number;\n  sourceUrl: string;\n}\n\n"
    "export const PAL_DUNGEON_BOSSES: Record<string, readonly DungeonBossEvidence[]> = "
    + j(dungeon_records)
    + ";\n\n"
    "export const DUNGEON_FAMILIES = "
    + j(dungeon_families)
    + ";\n\n"
    "export const DUNGEON_PROVENANCE = "
    + j(
        {
            "sourceTier": dungeon_payload.get("sourceTier", 3),
            "sourceKind": dungeon_payload.get("sourceKind", "wiki-sourced"),
            "indexUrl": dungeon_source.get("index", {}).get("url", "https://paldb.cc/en/Dungeons"),
            "families": len(dungeon_families),
            "pages": len(dungeon_source.get("pages", {})),
        }
    )
    + ";\n\n"
    "export function dungeonBossesOf(internalName: string): readonly DungeonBossEvidence[] {\n"
    "  return PAL_DUNGEON_BOSSES[internalName] ?? [];\n}\n",
)

# habitat
lines = [f"  {j(key)}: {j(recs[key].get('habitat', []))}," for key in keys]
write(
    "habitat.ts",
    "export interface HabitatWindow {\n  map: string;\n  time: \"day\" | \"night\";\n"
    "  count: number;\n}\n\n"
    "export const PAL_HABITAT: Record<string, HabitatWindow[]> = {\n"
    + "\n".join(lines)
    + "\n};\n\n"
    "export function habitatOf(internalName: string): HabitatWindow[] {\n"
    "  return PAL_HABITAT[internalName] ?? [];\n}\n",
)

# drops
lines = [f"  {j(key)}: {j(recs[key]['drops'])}," for key in keys]
write(
    "drops.ts",
    "export interface PalDrop {\n  item: string;\n  qty: string;\n"
    "  probability: string;\n  minLevel?: number;\n}\n\n"
    "export const PAL_DROPS: Record<string, PalDrop[]> = {\n"
    + "\n".join(lines)
    + "\n};\n\n"
    "export function dropsOf(internalName: string): PalDrop[] {\n"
    "  return PAL_DROPS[internalName] ?? [];\n}\n",
)

# active skills and partner skill
lines = []
for key in keys:
    record = recs[key]
    lines.append(
        "  %s: %s,"
        % (j(key), j({"partnerSkill": record.get("partnerSkill"), "activeSkills": record["activeSkills"]}))
    )
write(
    "skills.ts",
    "export interface ActiveSkill {\n  level: number;\n  name: string;\n"
    "  element?: string;\n  power?: number;\n  cooldown?: number;\n}\n\n"
    "export interface PalSkillBlock {\n  partnerSkill?: string | null;\n"
    "  activeSkills: ActiveSkill[];\n}\n\n"
    "export const PAL_SKILLS: Record<string, PalSkillBlock> = {\n"
    + "\n".join(lines)
    + "\n};\n\n"
    "export function skillsOf(internalName: string): PalSkillBlock {\n"
    "  return PAL_SKILLS[internalName] ?? { activeSkills: [] };\n}\n",
)

# gaps
write(
    "dataGaps.ts",
    "export interface DataGap {\n  internalName: string;\n  field: string;\n"
    "  reason: string;\n}\n\n"
    "export const DATA_GAPS: DataGap[] = " + j(gaps) + ";\n",
)
