/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DataCheckRouteImport } from './routes/data-check'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as OpinionsRouteImport } from './routes/opinions'
import { Route as TiersRouteImport } from './routes/tiers'
import { Route as CompendiumFieldAlphasRouteImport } from './routes/compendium/field-alphas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataCheckRoute = DataCheckRouteImport.update({
  id: '/data-check',
  path: '/data-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const OpinionsRoute = OpinionsRouteImport.update({
  id: '/opinions',
  path: '/opinions',
  getParentRoute: () => rootRouteImport,
} as any)
const TiersRoute = TiersRouteImport.update({
  id: '/tiers',
  path: '/tiers',
  getParentRoute: () => rootRouteImport,
} as any)
const CompendiumFieldAlphasRoute = CompendiumFieldAlphasRouteImport.update({
  id: '/compendium/field-alphas',
  path: '/compendium/field-alphas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data-check': typeof DataCheckRoute
  '/explore': typeof ExploreRoute
  '/opinions': typeof OpinionsRoute
  '/tiers': typeof TiersRoute
  '/compendium/field-alphas': typeof CompendiumFieldAlphasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data-check': typeof DataCheckRoute
  '/explore': typeof ExploreRoute
  '/opinions': typeof OpinionsRoute
  '/tiers': typeof TiersRoute
  '/compendium/field-alphas': typeof CompendiumFieldAlphasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data-check': typeof DataCheckRoute
  '/explore': typeof ExploreRoute
  '/opinions': typeof OpinionsRoute
  '/tiers': typeof TiersRoute
  '/compendium/field-alphas': typeof CompendiumFieldAlphasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data-check'
    | '/explore'
    | '/opinions'
    | '/tiers'
    | '/compendium/field-alphas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/data-check'
    | '/explore'
    | '/opinions'
    | '/tiers'
    | '/compendium/field-alphas'
  id:
    | '__root__'
    | '/'
    | '/data-check'
    | '/explore'
    | '/opinions'
    | '/tiers'
    | '/compendium/field-alphas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataCheckRoute: typeof DataCheckRoute
  ExploreRoute: typeof ExploreRoute
  OpinionsRoute: typeof OpinionsRoute
  TiersRoute: typeof TiersRoute
  CompendiumFieldAlphasRoute: typeof CompendiumFieldAlphasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-check': {
      id: '/data-check'
      path: '/data-check'
      fullPath: '/data-check'
      preLoaderRoute: typeof DataCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opinions': {
      id: '/opinions'
      path: '/opinions'
      fullPath: '/opinions'
      preLoaderRoute: typeof OpinionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiers': {
      id: '/tiers'
      path: '/tiers'
      fullPath: '/tiers'
      preLoaderRoute: typeof TiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compendium/field-alphas': {
      id: '/compendium/field-alphas'
      path: '/compendium/field-alphas'
      fullPath: '/compendium/field-alphas'
      preLoaderRoute: typeof CompendiumFieldAlphasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataCheckRoute: DataCheckRoute,
  ExploreRoute: ExploreRoute,
  OpinionsRoute: OpinionsRoute,
  TiersRoute: TiersRoute,
  CompendiumFieldAlphasRoute: CompendiumFieldAlphasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
