/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TiersRouteImport } from './routes/tiers'
import { Route as OpinionsRouteImport } from './routes/opinions'
import { Route as DataCheckRouteImport } from './routes/data-check'
import { Route as IndexRouteImport } from './routes/index'

const TiersRoute = TiersRouteImport.update({
  id: '/tiers',
  path: '/tiers',
  getParentRoute: () => rootRouteImport,
} as any)
const OpinionsRoute = OpinionsRouteImport.update({
  id: '/opinions',
  path: '/opinions',
  getParentRoute: () => rootRouteImport,
} as any)
const DataCheckRoute = DataCheckRouteImport.update({
  id: '/data-check',
  path: '/data-check',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data-check': typeof DataCheckRoute
  '/opinions': typeof OpinionsRoute
  '/tiers': typeof TiersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data-check': typeof DataCheckRoute
  '/opinions': typeof OpinionsRoute
  '/tiers': typeof TiersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data-check': typeof DataCheckRoute
  '/opinions': typeof OpinionsRoute
  '/tiers': typeof TiersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/data-check' | '/opinions' | '/tiers'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/data-check' | '/opinions' | '/tiers'
  id: '__root__' | '/' | '/data-check' | '/opinions' | '/tiers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataCheckRoute: typeof DataCheckRoute
  OpinionsRoute: typeof OpinionsRoute
  TiersRoute: typeof TiersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tiers': {
      id: '/tiers'
      path: '/tiers'
      fullPath: '/tiers'
      preLoaderRoute: typeof TiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opinions': {
      id: '/opinions'
      path: '/opinions'
      fullPath: '/opinions'
      preLoaderRoute: typeof OpinionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-check': {
      id: '/data-check'
      path: '/data-check'
      fullPath: '/data-check'
      preLoaderRoute: typeof DataCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataCheckRoute: DataCheckRoute,
  OpinionsRoute: OpinionsRoute,
  TiersRoute: TiersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
